<?php
    $helper = Mage::helper('testimonials');
    $testimonials = $this->getCollection();
?>

<div class="testimonials">

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <?php if($testimonials->getSize()):?>

        <h3><?php echo $this->__('Testimonials');?>:</h3>

        <?php if(Mage::getSingleton('customer/session')->isLoggedIn()):?>

            <button type="button" onclick="showTestimonialForm(this);"><?php echo $this->__('Add testimonial');?></button>

            <form id="testimonial-form" style="display: none;" action="<?php echo Mage::getUrl('testimonials/index/add');?>" method="post">
                <p><textarea name="testimonial" class="input-text required-entry"></textarea></p>
                <p><button type="submit"><?php echo $this->__('Add');?></button></p>
            </form>

            <script type="text/javascript">

                function showTestimonialForm(button) {
                    var form = $('testimonial-form');

                    if($(form).visible()) {
                        form.hide();
                        button.innerHTML = '<?php echo $this->__('Add testimonial');?>';
                    } else {
                        form.show();
                        button.innerHTML = '<?php echo $this->__('Hide testimonial form');?>';
                    }
                }

                new VarienForm('testimonial-form');

            </script>

        <?php endif;?>

        <?php foreach($testimonials as $testimonial):?>
            <div>
                <label>
                    <a href="mailto:<?php echo $testimonial->getCustomerEmail();?>"><?php echo $testimonial->getCustomerEmail();?></a>
                    <?php echo $testimonial->getCustomerFirstName(), ' ', $testimonial->getCustomerLastName();?>
                </label>
                <div><?php echo $helper->getFormattedDate($testimonial->getCreatedAt());?></div>
                <div><?php echo $testimonial->getTestimonial();?></div>
            </div>
        <?php endforeach;?>

        <?php echo $this->getPagerHtml();?>

    <?php else:?>

        <p><strong><?php echo $this->__('There are no testimonials yet');?></strong></p>

    <?php endif;?>
</div>